### ISSUE TITLE
When importing this package, TS is not able to resolve the types

### ISSUE THREAD

**Issue by getsalty** [aliakbarazizi/headless-datepicker#13]
### Issue:  
Installing this package, then importing it in a `tsx` file is presenting errors related to lack of types.

### Environment Info: 
Windows, VSCode, Vite, React, Typescript

### Example of the issue:
https://stackblitz.com/edit/vitejs-vite-dakskx?file=src%2FApp.tsx

![image](https://github.com/aliakbarazizi/headless-datepicker/assets/836241/67cc2a9b-fd9f-4d9d-9104-7b0b25caf5ac)

As you can see in this example, other issues are present because now fields are implicitly 'any' as well (probably because the types were not imported).

**Comment by aliakbarazizi** [comment]
Hi,

Thank you for reporting this bugs, it should be fixed in `1.1.5`

https://codesandbox.io/p/sandbox/misty-butterfly-kllpys
