### ISSUE TITLE
input format bug

### ISSUE THREAD

**Issue by durimfetahaj** [aliakbarazizi/headless-datepicker#15]
Hi, 

I do not know if anyone had this problem or it is just me but when I let the Input format as default (  yyyy/MM/dd ) and you click outside to close the picker the day lowers for one. So if it is 29 and you close the picker by clicking outside the date changes to 28 so minus one. Although, this does not happen when the format is set to ( yyyy/MM/dd HH:mm ) 

thanks

**Comment by aliakbarazizi** [comment]
Hello, Thank you for reporting the issue.

I reproduce the issue and it should be fixed in new version, can you please confirm that?

**Comment by durimfetahaj** [comment]
> Hello, Thank you for reporting the issue.
> 
> I reproduce the issue and it should be fixed in new version, can you please confirm that?

yep perfect. It is working as it should now. Thank you!
