### ISSUE TITLE
Need Option to Manually Trigger Click Event for Items

### ISSUE THREAD

**Issue by alizadeh118** [aliakbarazizi/headless-datepicker#17]
Hi Aliakbar,

First of all, thanks for this awesome library.

Are there any ways to manually trigger the click event of an item?

Here is the UI and as you can see users should be able to select a date and then click on the apply button to close the datepick window. But now clicking on items triggers the close event automatically.

![datepicker](https://github.com/aliakbarazizi/headless-datepicker/assets/13087224/c4b9c999-95e5-441b-8538-651f058f6819)

Thanks.

**Comment by aliakbarazizi** [comment]
I was working on new feature that seems to help your issue too.

The new features has some breaking change please see the release note for upgrade your package.

For your problem, in new version the datepicker will not close by default when you selecting an item from the picker.
And for apply button you can use `action` and set it to `close` to achieve your goal.

I created a example you can see it here

https://codesandbox.io/p/sandbox/fervent-artem-ztcwl3?file=%2Fsrc%2FApp.tsx%3A44%2C37

I will close the issue as resolved, feel free to create a new issue if you still have problem.
