### ISSUE TITLE
Change dayNames not working [?]

### ISSUE THREAD

**Issue by brunoandradebr** [aliakbarazizi/headless-datepicker#27]
First of all nice project you made! I'm struggling to just change interface day names, I'm passing an array of names I want show in calendar but it is not changing. What am i loosing ? 

![image](https://github.com/user-attachments/assets/bd9b2a40-e90f-42ed-befa-4d3e41179ca8)

but it keep en-us names: 

![image](https://github.com/user-attachments/assets/1fb66596-a822-41fd-b430-0f438fcec486)

**Comment by aliakbarazizi** [comment]
Hi again, thank you.

It should be fixed in latest release.

**Comment by aliakbarazizi** [comment]
You can check it out [here](https://codesandbox.io/p/devbox/headless-datepicker-q2xhsq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzf7dq7c00072a69d33q141c%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzf7dq7c00022a69irdlegrs%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzf7dq7c00042a69mgn7vtzt%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzf7dq7c00062a69wp5nfwct%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzf7dq7c00022a69irdlegrs%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzf7dq7c00012a69gfixme7u%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clzf7isn000022a69kjqz50sv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A17%252C%2522startColumn%2522%253A17%252C%2522endLineNumber%2522%253A17%252C%2522endColumn%2522%253A17%257D%255D%257D%255D%252C%2522id%2522%253A%2522clzf7dq7c00022a69irdlegrs%2522%252C%2522activeTabId%2522%253A%2522clzf7isn000022a69kjqz50sv%2522%257D%252C%2522clzf7dq7c00062a69wp5nfwct%2522%253A%257B%2522id%2522%253A%2522clzf7dq7c00062a69wp5nfwct%2522%252C%2522activeTabId%2522%253A%2522clzf7it3p00082a697i06w1jd%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzf7dq7c00052a69i2cg8058%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clzf7etdl00152a69wpjoxdnb%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522SETUP_TASKS%2522%252C%2522id%2522%253A%2522clzf7it3p00082a697i06w1jd%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clzf7dq7c00042a69mgn7vtzt%2522%253A%257B%2522id%2522%253A%2522clzf7dq7c00042a69mgn7vtzt%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzf7dq7c00032a69uq8ip59q%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520install%2520headless-datetimepicker%25403.0.3%2522%252C%2522id%2522%253A%2522clzf9byz000fy2a69pd57qgcp%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clzf7dq7c00032a69uq8ip59q%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by brunoandradebr** [comment]
> Hi again, thank you.
> 
> First make sure the config object is same in all renders.
> 
> > The configuration object should remain unchanged during React re-renders to maintain consistent behavior, and it's recommended to declare it outside the component to avoid unnecessary re-creations.
> 
> to do that just move config outside the component.
> 
> It should be fixed in latest release.

I'll give a try. your link is broken.
