### ISSUE TITLE
isInCurrentMonth inverted

### ISSUE THREAD

**Issue by brunoandradebr** [aliakbarazizi/headless-datepicker#28]
I think there is a bug with item.isInCurrentMonth, days in month is returning false and not in month returning true =(

![image](https://github.com/user-attachments/assets/a13cfe8a-390d-4c96-b034-f6b4b186f06a)

**Comment by aliakbarazizi** [comment]
Hi, You are correct, I figured out the problem and it should be fixed in latest release.
