### ISSUE TITLE
render bug ?

### ISSUE THREAD

**Issue by brunoandradebr** [aliakbarazizi/headless-datepicker#33]
I think that on config prop change is not triggering rendering. I'm trying to change locale names when user change language but it keep initial config object.

**Comment by aliakbarazizi** [comment]
> I think that on config prop change is not triggering rendering. I'm trying to change locale names when user change language but it keep initial config object.

initial config is can't be controlled, since it need to change everything, best is to use react `key` prop to re render the whole component

also worse to mention I mentioned it in readme

> The configuration object should remain unchanged during React re-renders to maintain consistent behavior, and it's recommended to declare it outside the component to avoid unnecessary re-creations.
